### ISSUE TITLE
favicon.ico not found

### ISSUE THREAD

**Issue by jaydee73** [gutmensch/docker-dmarc-report#25]
Hi folks,

I've just installed the docker container for the very first time (on my Synology NAS). It seems to run, but every time I visit the webpage, I'll get this error message in the container log:

2022/10/02 07:42:25 [error] 27#27: *1609 open() "/var/www/viewer/favicon.ico" failed (2: No such file or directory), client: 172.19.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "localIP:8080", referrer: "http://localIP:8080/"

Is this an issue of my installation, of your docker container or of the report viewer from techsneeze?

Greetings,
JD

**Comment by jaydee73** [comment]
Addition: I do get another icon-error (apple touch icon.png). Seems that there are missing some in /var/www/viewer/. When I look into the directory, I can see four png-files, but obviously not the mentioned ones. But why?

**Comment by gutmensch** [comment]
Hey @jaydee73, this is a pretty common non-critical error. In essence: every web browser or mobile app client (e.g. apple safari, apple site association) try by default some standard icons for local display functionality -- if it's not found the browser/client just displays a default. Neither the used open source software used here nor the image itself are caring about this, because it means quite a lot of work to implement for every different OS/client/browser combination.

To add to the explanation: The erroring files you are seeing are not referenced by the code itself. These are rogue requests from (browser) clients, unrelated to the image source. So your image is likely just working fine.

**Comment by jaydee73** [comment]
Ok, got it. Thanks for the clarification. 

I (maybe) have another issue as currently .xml.gz reports (from yahoo) are not processed properly. They are moved to the error-folder. 

But I will dig deeper into this first and then raise another issue if necessary.

Thanks,
JD
